variables:
  Project: hk591-ui
  ProjecHtdocsDir: /home/htdocs/dist
  ProjectName: ${Project}-${CI_COMMIT_REF_NAME}
  ProjectDir: ${HtdocsDir}/${Project}-${CI_COMMIT_REF_NAME}
  ProjectBuildDir: ${HtdocsDir}_191/${Project}-${CI_COMMIT_REF_NAME}
  IMAGE: hub.591.com.tw/nginx-alpine:hk591-ui-${CI_COMMIT_REF_NAME}
  replicas: "1"
  
stages:
  - build
  - buildshell
  - BuildDocker
  - deploy

job_build_master:
  stage: build
  script:
    - sh _gitlabci/build.sh
  only:
    - master
  tags:
    - tw591-runner-php7211-node10-nfs41-new
    
job_buildshell_master:
  stage: buildshell
  script:
    - sh _gitlabci/buildshell.sh
  only:
    - master
  tags:
    - tw591-runner-php7211-node10-nfs41-new
    
job_BuildDocker_master:
  stage: BuildDocker
  script:
    - sh _gitlabci/BuildDocker.sh
  only:
    - master
  tags:
    - tw591-runner-php7211-node10-nfs41-new
    
job_deploy_master:
  stage: deploy
  script:
    - sh _gitlabci/deploy.sh
  only:
    - master
  tags:
    - tw591-runner-php7211-node10-nfs41-new
    

    
